sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t owenyi3207/docker-react-app -f Dockerfile.dev ./

script:
  - docker run -e CI=true owenyi3207/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-310881911728"
  bucket_path: "docker-react-app"
  on:
    branch: main
    
access_key_id: $AWS_ACCESS_KEY_ID
secret_access_key: $AWS_SECRET_ACCESS_KEY

# after_success:
#   - echo "Test success"